### PR TITLE
add mozilla logo to add-on

### PR DESCRIPTION
**Pull request by ericawright**
screen shot 2018-09-07 at 2 58 23 pm

Fixes: #56

### CODE REVIEW

**Comment by groovecoder** [comment]
Lovely!

**Comment by pdehaan** [comment]
Interesting... I see it in about:debugging (via <kbd>$ npm start</kbd> using Nightly), but I'm seeing it flash+disappear in about:addons (overview and details pages):

aboot_debugging

---

aboot_addons_1_

aboot_addons_2_

**Comment by ericawright** [comment]
@pdehaan, that's odd, and upsetting

**Comment by pdehaan** [comment]
Icon isn't appearing in about:addons on Win 10 using signed v1.0.3 add-on either.

**Comment by pdehaan** [comment]
The logo was fixed in #80

**Pull request merged**
